name: Verify

on:
  push:
    branches:
      - "main"

jobs:
  verify:
    name: Verify

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.3
      - name: Install packages
        run: pnpm i
      - name: Build packages
        run: pnpm build:packages
      - name: Run tests
        run: pnpm test
      - name: Type check
        run: pnpm check

  verify-bun:
    name: Verify (bun)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.3
      - name: Install packages
        run: pnpm i
      - name: Build packages
        run: pnpm build:packages
      - name: Run tests
        run: bun run test
      - name: Type check
        run: bun run check
